version: 2.1

workflows:
  test: 
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    
    steps:
      - checkout
      - run:
          name: Setup
          command: pip install tox
      - run:
          name: Run tests
          command: tox
