version: 2.1

orbs:
  windows: circleci/windows@2.4.1

workflows:
  test: 
    jobs:
      - test
      - wintest

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    
    steps:
      - checkout
      - run:
          name: Setup
          command: pip install tox
      - run:
          name: Run tests
          command: tox

  wintest:
    executor:
      name: windows/default
      size: medium
    steps:
      - checkout
      - run: 'Write-Host ''Hello, Windows'''
