version: 2.1

workflows:
  test: 
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    parallelism: 4
    
    steps:
      - checkout
      - run:
          name: Setup
          command: pip install tox
      - run:
          name: Run tests
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "tests/test_*.py" | circleci tests split)
            tox -- $TEST_FILES
