version: 2.1

workflows:
  test: 
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    parallelism: 4
    
    steps:
      - checkout
      - run:
          name: Setup
          command: pip install tox
      - run:
          name: Run tests
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "tests/test_*.py" | circleci tests split --split-by=timings)
            mkdir -p test-results
            tox -- --junitxml=test-results/junit.xml $TEST_FILES
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
